### ISSUE TITLE
Make ontologies available in standalone repository, to include with git sub modules

### ISSUE THREAD

**Issue by damooo** [zazuko/rdf-vocabularies#116]
Thanks for great work.

It would be great if `ontologies` folder itself is available as separate git repository. We can still include it as a folder for all practical purposes using git-sub-modules. This will enable to include same stack-agnostic ontologies in any repository with any language stack.

**Comment by tpluscode** [comment]
Thank you @damooo. This is a good idea but not immediately possible since it would require a little more reorganisation of how we author this package

**Comment by tpluscode** [comment]
Ultimately, I think I will close this. The repository gets a solid revamp and extracting the ontology quads to a separate repo is not something we intend to do
