### ISSUE TITLE
Request for new vocabularies

### ISSUE THREAD

**Issue by damooo** [zazuko/rdf-vocabularies#117]
Namaste all.  It is a request for few vocabularies. These are mainly used for implementing solid specifications. These all vocabs have prefix.cc registered prefixes, and ther namespace base iri de-references to their ontology files

|prefix|title|description|uri|
|-------|-----|---------------|-----------------------|
|[cert](http://prefix.cc/cert)|The Cert Ontology 1.0|Ontology for Certificates|[https://www.w3.org/ns/auth/cert#](https://www.w3.org/ns/auth/cert#)|
|[stat](http://prefix.cc/stat)|POSIX stat|Describes terms for POSIX-like files and directory listings|[http://www.w3.org/ns/posix/stat#](http://www.w3.org/ns/posix/stat#)|
|[solid](http://prefix.cc/solid)|Solid Terms|The Solid Terms vocabulary defines terms referenced in Solid specifications.|[http://www.w3.org/ns/solid/terms#](http://www.w3.org/ns/solid/terms#)|
|[oidc](http://prefix.cc/oidc)|Solid OIDC|The OpenID Connect vocabulary used by the Solid-OIDC authentication specification.|[http://www.w3.org/ns/solid/oidc#](http://www.w3.org/ns/solid/oidc#)|
|[pim](http://prefix.cc/pim)|Workspace Ontology|This ontology is for use in describing Workspaces.|[http://www.w3.org/ns/pim/space#](http://www.w3.org/ns/pim/space#)|

Thanks again for your work

**Comment by tpluscode** [comment]
Hello @damooo. We appreciate your interest in our package. Related to your earlier issue #116, we are still considering how to proceed with this package. It has been already noted in the past that size is a factor here and adding more and more prefixes will just keep it growing.

Also, there is the matter of having one or multiple such packages. I kind feel like we might be getting a little overboard here cramming all vocabularies together. 

That said, you might be interested in a template repository I created based `rdf-vocabularies`: https://github.com/zazuko/build-your-vocabularies. It comes prepared with all the necessary setup for creating analogous packages with your personalised or project-related selection of vocabularies. As a bonus, the resulting package will also export namespace dedicated builders, such as can be found in [@tpluscode/rdf-ns-builders](https://www.npmjs.com/package/@tpluscode/rdf-ns-builders).

The readme has all the necessary details and you can also refer to https://github.com/hypermedia-app/vocabularies to see it used in practice

**Comment by ktk** [comment]
The current plan for refactoring is #118 and I think we should continue to add more ontologies once we did the split. It might be "over board" but at the same time it seems to be useful for others than just us so why not extend the repo with all ontologies to whatever people need.

**Comment by tpluscode** [comment]
Just published packages [`@vocabulary/cert`](https://npm.im/@vocabulary/cert), [`@vocabulary/oidc`](https://npm.im/@vocabulary/oidc), [`@vocabulary/pim`](https://npm.im/@vocabulary/pim), [`@vocabulary/solid`](https://npm.im/@vocabulary/solid) and [`@vocabulary/stat`](https://npm.im/@vocabulary/stat). The vocabs will soon be added to prefix.zazuko.com
