### ISSUE TITLE
New ontology: metadata4ing

### ISSUE THREAD

**Issue by snickersnee22** [zazuko/rdf-vocabularies#126]
Hi zazuko team - is it possible to include the metadata4ing ontology in your prefix lookup service? You can find details on the ontology here:

http://metadata4ing.org

Serializations in different formats are also available via that link.

Thanks and kind regards, Marc

**Comment by tpluscode** [comment]
[`@vocabulary/m4i`](https://npm.im/@vocabulary/m4i) is now published and will soon be added to prefix.zazuko.com
