### ISSUE TITLE
Update request: New release for m4i

### ISSUE THREAD

**Issue by doigl** [zazuko/rdf-vocabularies#199]
Dear zazuko-Team,

there is a new release for Metadata4Ing: https://w3id.org/nfdi4ing/metadata4ing/1.3.0/

We wanted to let you know and ask whether you could update here/ for the zazuko prefix service.

Thank you and all the best form the m4i working group,

Dorothea

**Comment by tpluscode** [comment]
Thank you for notifying. I updated and published now. Will update the prefix server in a moment
