### ISSUE TITLE
Add prefix & namespace metadata to each file

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-vocabularies#27]
Good idea via @semanticfire, we should add two more quads to each vocabulary dump to describe the prefix & namespace we use for it.

Bart proposed using [vann](http://vocab.org/vann/) but I can't seem to fetch an RDF version of it anymore, the links are dead.

Ivan is using the RDFa vocabulary for this, see for example [here](https://github.com/uduvudu/uv-context/blob/master/rdf/uduvudu-context.ttl#L73-L74). So my proposal would be to add these two quads using the RDFa vocabulary.

**Comment by vhf** [comment]
I think this would be a "big" change to what this package provides. The triples from the ontologies are currently provided as-is, nothing gets added or removed or modified.

What about providing a separate file with all the metadata as RDF instead? It could provide the base IRI, prefix, and filename.

**Comment by ktk** [comment]
That would be perfectly fine for me. Sole question is what URI would we use as subject for this. In RDFa initial context it's a blank node, maybe that's the best bet. But then we should probably also add a class as in the example, they use `rdfa:PrefixMapping`

**Comment by vhf** [comment]
Alright so something like:
```turtle
[] a rdfa:PrefixMapping ;
  dcterms:description "The W3C Linked Data Platform (LDP) Vocabulary" ;
  rdfs:isDefinedBy <http://www.w3.org/2012/ldp> ;
  rdfa:prefix "ldp" ;
  rdfa:uri "http://www.w3.org/ns/ldp#" .
```

and one more thing for the local filename I guess

**Comment by ktk** [comment]
Looks good! For file the only ontology I know is infamous Nepomuk File Ontology, which was once part of KDE: http://oscaf.sourceforge.net/nfo.html#nfo:fileName.

Could not find something else with a quick search for file*

**Comment by vhf** [comment]
What about [`dbo:filename`](http://dbpedia.org/ontology/filename)?

More questions on this example:
```turtle
[] a rdfa:PrefixMapping ;
  dcterms:description "The W3C Linked Data Platform (LDP) Vocabulary" ;
  rdfs:isDefinedBy <http://www.w3.org/2012/ldp> ;
  rdfa:prefix "ldp" ;
  rdfa:uri "http://www.w3.org/ns/ldp#" ;
  dbo:filename "ontologies/ldp.nq" .
```

* What's the difference between the content we would put in `rdfs:isDefinedBy` and `rdfa:uri`?
* Where can I find what to put in `dcterms:description`?

My idea is to add these to https://github.com/zazuko/rdf-vocabularies/blob/master/overrides.js or to a file similar to this one, to then be able to generate the above data.

**Comment by ktk** [comment]
* [dcterms:description](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-description)
* `rdfs:isDefinedBy` vs. `rdfa:uri`: From what I read they aim at the same thing IMO. I would prefer `rdfs:` as I rarely see the `rdfa` one in the wild.
* `dbo:filename` sounds close enough!

**Comment by vhf** [comment]
Thoughts on: https://github.com/zazuko/rdf-vocabularies/blob/b939bd4b5d50d08f1994ab75e885159af99eacf0/ontologies/_index.nq ?

**Comment by vhf** [comment]
Ping @ktk @semanticfire

**Comment by ktk** [comment]
From triple POV looks good to me!

**Comment by vhf** [comment]
`v2019.12.23`
