### ISSUE TITLE
Add SHACL

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-vocabularies#36]
Somehow we completely missed SHACL

https://www.w3.org/TR/shacl/

**Comment by vhf** [comment]
Is that it: https://github.com/w3c/data-shapes/blob/gh-pages/shacl/shacl.ttl?

Which prefix should it be, `sh`?

**Comment by ktk** [comment]
Yes, prefix is `sh`. For the file I see this in raw, not sure what URI makes more sense: https://raw.githubusercontent.com/w3c/data-shapes/gh-pages/shacl/shacl.ttl

**Comment by ktk** [comment]
I've created an issue and asked why I can't get that directly https://github.com/w3c/data-shapes/issues/118

**Comment by TallTed** [comment]
Have you tried getting [Turtle serialization of the SHACL vocabulary](http://www.w3.org/ns/shacl.ttl), as linked from [the SHACL spec](https://www.w3.org/TR/shacl/#constraints-section)?

**Comment by ktk** [comment]
@TallTed ah thanks for the hint, I did search for "ttl" in the file but not for Turtle :-D

**Comment by ktk** [comment]
@vhf I checked again, looks like I did not reference the proper URI before. It works fine with `http://www.w3.org/ns/shacl#` for me, I get Turtle back. So adding the prefix & namespace should be enough, no need to override the file.
