### ISSUE TITLE
Add SemWeb Vocab Status ontology

### ISSUE THREAD

**Issue by tpluscode** [zazuko/rdf-vocabularies#40]
Dereferencable here: http://www.w3.org/2003/06/sw-vocab-status/ns#

Is it any popular? Hydra uses it to annotate its terms.

additionally, I'm thinking that the prefix server could actually take advantage of this and/or similar annotations to highlight deprecated terms

**Comment by ktk** [comment]
Looks like this was added long time ago with prefix `vs`. Closing
