### ISSUE TITLE
W3C Block

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-vocabularies#49]
Apparently we get blocked fast by w3c.org while fetching the data. @vhf how fast/when does it happen? Maybe @iherman can help us out here.

Ivan, we fetch RDF vocabularies in an automated way every few months and add the latest RDF versions of it in this repository. That seems to be enough to get the IP blocked by W3C for a while.

**Comment by vhf** [comment]
I cannot trigger it today. Last few times my IP got banned from w3.org for ~1-2h after requesting ~5 files in ~3 minutes.

**Comment by iherman** [comment]
@ktk, can you send me your email address (I am at ivan@w3.org) to get you in contacts with our system people? It is fairly difficult to say anything without any further details, and I am not sure it is appropriate to get into such details on a public issue.

**Comment by ktk** [comment]
@iherman ygm

**Comment by vhf** [comment]
Closing this for now, the rules seem to have been relaxed quite a bit, at least I'm not getting banned anymore.
