### ISSUE TITLE
Rename dc11 to dc?

### ISSUE THREAD

**Issue by vhf** [zazuko/rdf-vocabularies#52]
Do we want to rename [`dc11`](https://github.com/zazuko/rdf-vocabularies/blob/12248415644a9b0d68a85e537cf36f2c799e7c4d/src/lib/prefixes.ts#L8) to `dc`?

**Comment by ktk** [comment]
So the whole history with Dublin Core is a bit complicated, from the [Wikipedia page](https://en.wikipedia.org/wiki/Dublin_Core):

> Since 2012, the two have been incorporated into the DCMI Metadata Terms as a single set of terms using the RDF data model.[13] The full set of elements is found under the namespace http://purl.org/dc/terms/. Because the definition of the terms often contains domains and ranges, which may not be compatible with the pre-RDF definitions used for the original 15 Dublin Core elements, there is a separate namespace for the original 15 elements as previously defined: http://purl.org/dc/elements/1.1/

I've always read that as we should prefer the [DCMI Metadata Terms](https://prefix.zazuko.com/prefix/dcterms:) while using RDF, as they were designed with RDF in mind. The 15 "old" elements should only be used if there is no better alternative available.

Unfortunately there is a lot of confusion about that in the real world, prefixes is just one of them. I've seen any kind of prefixes around "dc" for both terms and elements and in the end we use  `dc11` for the elements so far, as this is what the [RDFa Initial Prefix](https://www.w3.org/2011/rdfa-context/rdfa-1.1) set defines. In this list you can see that they even use `dc` and `dcterms` for the terms and for the elements they use `dc11`.

So my personal opinion:
* If we rename anything, we should rename `dcterms` to `dc`
* Elements should IMO stay on something not common like `dc11` as it should not be used for new stuff ideally
