### ISSUE TITLE
DBpedia prefixes

### ISSUE THREAD

**Issue by tpluscode** [zazuko/rdf-vocabularies#54]
I thought we might add prefixes for the non-vocabulary DBpedia namespaces:

```json
{
  "dbr": "http://dbpedia.org/resource/",
  "yago": "http://dbpedia.org/class/yago/",
  "yago-res": "http://yago-knowledge.org/resource/"
}
```

Not too sure about the YAGO stuff though...

**Comment by ktk** [comment]
Just as namespace without the ontology I guess? If so we should probably add all the wikidata namespaces as well (and skip the import in the override)

**Comment by tpluscode** [comment]
In hindsight, these probably do not have a place in the vocabulary packages
