### ISSUE TITLE
Using the package in browser environment

### ISSUE THREAD

**Issue by tpluscode** [zazuko/rdf-vocabularies#7]
I would like to be able to use this package's functionality in the browser. Currently the biggest obstacle is using node.js filesystem APIs (`fs` and `path`).

I propose to split the ontology code from the loading code so that it can be substituted with different code for the browser. I have two ideas:

1. Simpler, to use `fetch`. The problem here is that the files have to be fetched from somewhere. Either raw.github URLs or manually added to the deployed app.
1. Use dynamic imports, which forces some additional effort on the consumer to set up webpack or similar to handle

**Comment by vhf** [comment]
Cf. #8 

Published in `v2019.6.17`.
