### ISSUE TITLE
Using expand requires raw-loader

### ISSUE THREAD

**Issue by tpluscode** [zazuko/rdf-vocabularies#76]
When the `@zazuko/rdf-vocabularies/expand` module is imported in a web project, webpack will try to create chunks for all the vocabularies because the `expandWithCheck` is dynamically loaded and it pull the n-quad sources.

With `raw-loader` added the bundle sizes explode.

Probably the only way would be to separate the `expand` and `expandWithCheck` modules. What do you think @vhf?

**Comment by vhf** [comment]
Let's do this if that's the only way. I don't know much about webpack and I trust your judgment.
