### ISSUE TITLE
Bug: buildPath returning incorrect path

### ISSUE THREAD

**Issue by alexkreidler** [zazuko/rdf-vocabularies#81]
![ontology_debug](https://user-images.githubusercontent.com/11166947/102132740-047c5780-3e22-11eb-85b4-5bdbfdf7b34b.png)

buildPath is returning `node_modules/@zazuko/ontologies` instead of the correct `node_modules/@zazuko/rdf-vocabularies/ontologies`.

Additionally, the `vocabularies()` function should properly throw an error if it reads files in the wrong location.

Thanks for this tool!

**Comment by alexkreidler** [comment]
I patched the code by replacing
```
path_1.join(__dirname, '../../ontologies', \`${prefix}.nq\`)
// with
path_1.join(__dirname, '../ontologies', `${prefix}.nq`)
```
![patch](https://user-images.githubusercontent.com/11166947/102133159-abf98a00-3e22-11eb-87ff-70280cbbe2be.png)

See that dataset returns proper data, whereas before it returned an empty object.
![after_patch](https://user-images.githubusercontent.com/11166947/102133160-abf98a00-3e22-11eb-9551-b95950bbc41b.png)

I don't know if this is new bug in a new release or there are some other mitigating factors that might be why I am specifically getting this bug.

**Comment by tpluscode** [comment]
Thank you @alexkreidler, I noticed that too. TL;DR; the paths are different in dev (`./src`) than in the built package. You'll see that I started #80 but it's not done yet.

For the time being you might instead import from `@zazuko/rdf-vocabularies/datasets` or `@zazuko/rdf-vocabularies/datasets/prefix`
